server:
  port: 8002

somnia:
  config:
#    base-package: io.ep2p.somnia.sample
    mongo-key-index-name: sample-index
    decentralized:
      minimum-distribution: 10

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: somnia-sample-1